### ISSUE TITLE
Server Bug

### ISSUE THREAD

**Issue by PaladinFallen** [casperge/RealisticSeasons-issues#165]
[19:54:00] [Server thread/WARN]: [RealisticSeasons] Task #137 for RealisticSeasons v9.1.13 generated an exception
java.lang.NumberFormatException: For input string: "CUSTOM" under radix 16
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.valueOf(Integer.java:973) ~[?:?]
	at java.lang.Integer.decode(Integer.java:1458) ~[?:?]
	at java.awt.Color.decode(Color.java:731) ~[?:?]
	at me.casperge.realisticseasons.utils.JavaUtils.mixColor(JavaUtils.java:113) ~[RealisticSeasons-9.1.13.jar:?]
	at me.casperge.realisticseasons.data.BiomeFileLoader.registerMixedColorBiomes(BiomeFileLoader.java:634) ~[RealisticSeasons-9.1.13.jar:?]
	at me.casperge.realisticseasons.data.BiomeFileLoader.load(BiomeFileLoader.java:127) ~[RealisticSeasons-9.1.13.jar:?]
	at me.casperge.realisticseasons.data.BiomeFileLoader.<init>(BiomeFileLoader.java:46) ~[RealisticSeasons-9.1.13.jar:?]
	at me.casperge.realisticseasons.RealisticSeasons.enable(RealisticSeasons.java:186) ~[RealisticSeasons-9.1.13.jar:?]
	at me.casperge.realisticseasons.RealisticSeasons$1.run(RealisticSeasons.java:149) ~[RealisticSeasons-9.1.13.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-86]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1138) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-86]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by casperge** [comment]
Thank you for reporting, will be fixed today
