### ISSUE TITLE
Warning when new players join the server for the first time

### ISSUE THREAD

**Issue by Illusionika** [casperge/RealisticSeasons-issues#172]
This happened about two weeks ago

Now every new player joins the server with a warning, but the plugin seems to be working

> [12:32:30 INFO]: Welcome Inner_furnace to our server!
[12:32:30 INFO]: Inner_furnace joined the game
[12:32:30 INFO]: Inner_furnace[/183.193.180.23:49288] logged in with entity id 178036 at ([world]-57.5, 85.0, 89.5)
[12:32:30 WARN]: java.net.ConnectException: 拒绝连接
[12:32:30 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[12:32:30 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[12:32:30 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[12:32:30 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[12:32:30 WARN]:        at java.base/java.net.Socket.connect(Socket.java:639)
[12:32:30 WARN]:        at java.base/java.net.Socket.connect(Socket.java:588)
[12:32:30 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[12:32:30 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
[12:32:30 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
[12:32:30 WARN]:        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
[12:32:30 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
[12:32:30 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
[12:32:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1312)
[12:32:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1245)
[12:32:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1131)
[12:32:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1060)
[12:32:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1668)
[12:32:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592)
[12:32:30 WARN]:        at java.base/java.net.URL.openStream(URL.java:1161)
[12:32:30 WARN]:        at RealisticSeasons-10.0.4.jar//me.casperge.realisticseasons.utils.JavaUtils.getHttp(JavaUtils.java:184)
[12:32:30 WARN]:        at RealisticSeasons-10.0.4.jar//me.casperge.realisticseasons.utils.JavaUtils.getGeoLocationCountryCode(JavaUtils.java:170)
[12:32:30 WARN]:        at RealisticSeasons-10.0.4.jar//me.casperge.realisticseasons.event.EntityEvents$1$1.run(EntityEvents.java:171)
[12:32:30 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:32:30 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:32:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:32:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:32:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:32:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by casperge** [comment]
Thank you, will be fixed in the next update
