### ISSUE TITLE
Errors on join in disabled Worlds

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [casperge/RealisticSeasons-issues#173]
Paper version: `git-Paper-81 (MC: 1.19)`
RealisticSeasons version: `10.0.6`

RealisticSeasons throws errors in console whenever someone join a world where RS is disabled. I enabled it and rejoined with no errors. When disabled again, the error returns.

It seems that after rebooting, if RS is disabled in the world, the errors are many more (about 900 lines total compared to 21~ per error on joins after the first).

```
[RealisticSeasons] Unhandled exception number 512 occurred in onPacketSending(PacketEvent) for RealisticSeasons
java.lang.NullPointerException: Cannot invoke "me.casperge.realisticseasons.season.SubSeason.getPhase()" because "<local7>" is null
        at me.casperge.realisticseasons.event.ChunkPacketEventProtocolLib1_19_R1$1.onPacketSending(ChunkPacketEventProtocolLib1_19_R1.java:70) ~[RealisticSeasons-10.0.6.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2073) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2059) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.trackChunk(ServerPlayer.java:2201) ~[?:?]
        at net.minecraft.server.level.ChunkMap.playerLoadedChunk(ChunkMap.java:2184) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.level.ChunkMap.updateChunkTracking(ChunkMap.java:1648) ~[paper-1.19.jar:git-Paper-81]
        at io.papermc.paper.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:875) ~[paper-1.19.jar:git-Paper-81]
        at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:584) ~[paper-1.19.jar:git-Paper-81]
        at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:741) ~[paper-1.19.jar:git-Paper-81]
        at io.papermc.paper.chunk.PlayerChunkLoader.tick(PlayerChunkLoader.java:515) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:907) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:647) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by casperge** [comment]
Hello, thank you for the error and the information. Are sub-seasons disabled on your server?

**Comment by ProfessionalBoatDrifter** [comment]
I'm happy to help :)

Sub-seasons are not disabled.

**Comment by casperge** [comment]
Thank you, working on a fix

**Comment by casperge** [comment]
Should be fixed in the latest version
