### ISSUE TITLE
Minecraft Clients crash upon joining server with RealisticSeasons

### ISSUE THREAD

**Issue by ghost** [casperge/RealisticSeasons-issues#185]
[crash-2022-12-24_11.16.44-client.txt](https://github.com/casperge/RealisticSeasons-issues/files/10298371/crash-2022-12-24_11.16.44-client.txt)
Hey,
Whenever someone joins my server, they'll receive this crash.
Reproduction was fairly easy: Have RealisticSeasons installed and joining, but
some players noted that it only occured sporadically, and only during certain times of certain seasons (They couldn't give me more details)
I'm also sure its RS because whenever I disable it, the issue disappears.
I sadly have no idea what precisely could be causing it.

**Comment by casperge** [comment]
Hello, does this happen to everyone or only specific players?

**Comment by ghost** [comment]
Hey, it happened to everyone

**Comment by ArmonicPvP** [comment]
I have an issue like this as well. Related to ProtocolLib where players are getting this error:

[31.12 22:57:42] [Server] [WARN] io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "trackedValues" is null
[31.12 22:57:42] [Server] [WARN] 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[31.12 22:57:42] [Server] [WARN] 	at TradeSystem_v2.1.3.jar//de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:86)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[31.12 22:57:42] [Server] [WARN] 	at TradeSystem_v2.1.3.jar//de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:86)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[31.12 22:57:42] [Server] [WARN] 	at TAB.v3.2.1.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:93)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[31.12 22:57:42] [Server] [WARN] 	at ProtocolLib-5.0.0-SNAPSHOT.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[31.12 22:57:42] [Server] [WARN] 	at ProtocolLib-5.0.0-SNAPSHOT.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[31.12 22:57:42] [Server] [WARN] 	at net.minecraft.network.Connection.doSendPacket(Connection.java:459)
[31.12 22:57:42] [Server] [WARN] 	at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433)
[31.12 22:57:42] [Server] [WARN] 	at ProtocolLib-5.0.0-SNAPSHOT.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[31.12 22:57:42] [Server] [WARN] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[31.12 22:57:42] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by casperge** [comment]
You have to contact ProtocolLib for this, doesn't look like a RealisticSeasons thing

**Comment by casperge** [comment]
> Hey, it happened to everyone

For your error, I released a potential fix a few weeks ago, did it fix anything?

**Comment by ghost** [comment]
Hey, sorry for my incredibly late response, the error disappeared.
