### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by ArmonicPvP** [casperge/RealisticSeasons-issues#186]
[31.12 21:48:38] [Server] [WARN] java.lang.NoSuchFieldException: b
[31.12 21:48:38] [Server] [WARN] 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[31.12 21:48:38] [Server] [WARN] 	at RealisticSeasons-10.2.1.jar//me.casperge.realisticseasons1_19_R2.NmsCode_19_R2.sendPacket(NmsCode_19_R2.java:358)
[31.12 21:48:38] [Server] [WARN] 	at RealisticSeasons-10.2.1.jar//me.casperge.realisticseasons1_19_R2.FakeArmorStand_1_19_R2.move(FakeArmorStand_1_19_R2.java:84)
[31.12 21:48:38] [Server] [WARN] 	at RealisticSeasons-10.2.1.jar//me.casperge.realisticseasons.particle.entity.FallingLeaf.tick(FallingLeaf.java:103)
[31.12 21:48:38] [Server] [WARN] 	at RealisticSeasons-10.2.1.jar//me.casperge.realisticseasons.particle.ParticleManager$1.run(ParticleManager.java:79)
[31.12 21:48:38] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[31.12 21:48:38] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[31.12 21:48:38] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[31.12 21:48:38] [Server] [WARN] 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[31.12 21:48:38] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[31.12 21:48:38] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[31.12 21:48:38] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[31.12 21:48:38] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by casperge** [comment]
Updating should fix this
