### ISSUE TITLE
player can't see anything after the console error

### ISSUE THREAD

**Issue by minecraft-dripdrop** [casperge/RealisticSeasons-issues#204]
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: Exception in thread "RealisticSeasons-ChunkPacketProcessor" java.lang.IndexOutOfBoundsException: readerIndex(16685) + length(2) exceeds writerIndex(16685): UnpooledHeapByteBuf(ridx: 16685, widx: 16685, cap: 16685/16685)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at net.minecraft.network.PacketDataSerializer.readShort(PacketDataSerializer.java:1294)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at net.minecraft.world.level.chunk.ChunkSection.a(ChunkSection.java:273)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at RealisticSeasons-10.5.6.jar//me.casperge.realisticseasons1_20_R1.ProtocolLibUtils1_20_R1.extractDataSafe(ProtocolLibUtils1_20_R1.java:199)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at RealisticSeasons-10.5.6.jar//me.casperge.realisticseasons1_20_R1.ProtocolLibUtils1_20_R1.readPacketOld(ProtocolLibUtils1_20_R1.java:92)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at RealisticSeasons-10.5.6.jar//me.casperge.realisticseasons1_20_R1.ProtocolLibUtils1_20_R1.readPacket(ProtocolLibUtils1_20_R1.java:77)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at RealisticSeasons-10.5.6.jar//me.casperge.realisticseasons.event.ChunkPacketProcessor.handleEntry(ChunkPacketProcessor.java:46)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at RealisticSeasons-10.5.6.jar//me.casperge.realisticseasons.event.ChunkPacketProcessor.run(ChunkPacketProcessor.java:29)
[22:22:48] [RealisticSeasons-ChunkPacketProcessor/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

After the console sends out this error. 
A lot of players say they can't see anything, it's like they're in the void. 
So I join the server, and I ended up the same way

![QQ图片20230704223554](https://github.com/casperge/RealisticSeasons-issues/assets/62246956/6325063e-906b-4d79-8485-98b59e7d988c)

**Comment by casperge** [comment]
Just fixed in v10.5.7

**Comment by minecraft-dripdrop** [comment]
> Just fixed in v10.5.7

Well, what a coincidence, I just encountered this bug, feedback bug finished actually fixed
