### ISSUE TITLE
crashing server

### ISSUE THREAD

**Issue by Endernik** [casperge/RealisticSeasons-issues#219]
[19:32:32] [Craft Scheduler Thread - 137 - RealisticSeasons/WARN]: [RealisticSeasons] Plugin RealisticSeasons v10.6.1 generated an exception while executing task 663560
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:809) ~[?:?]
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:152) ~[?:?]
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:147) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:147) ~[?:?]
	at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:500) ~[?:?]
	at sun.net.www.http.HttpClient.finished(HttpClient.java:452) ~[?:?]
	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:101) ~[?:?]
	at sun.net.www.MeteredStream.justRead(MeteredStream.java:95) ~[?:?]
	at sun.net.www.MeteredStream.read(MeteredStream.java:142) ~[?:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3711) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:329) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:396) ~[?:?]
	at me.casperge.realisticseasons.utils.JavaUtils.getHttp(JavaUtils.java:187) ~[RealisticSeasons-10.6.1.jar:?]
	at me.casperge.realisticseasons.utils.JavaUtils.getGeoLocationCountryCode(JavaUtils.java:170) ~[RealisticSeasons-10.6.1.jar:?]
	at me.casperge.realisticseasons.event.EntityEvents$1$1.run(EntityEvents.java:151) ~[RealisticSeasons-10.6.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by casperge** [comment]
Hello Endernik, can you share a paper heap dump file? You can generate one using `/paper heap`. It will give me more information about what is going wrong in your server's memory.
