### ISSUE TITLE
Task #7431 for RealisticSeasons V10.6.4 generated an exception

### ISSUE THREAD

**Issue by TomatoTTV** [casperge/RealisticSeasons-issues#224]
1. when first starting the server it spits out the following:
       [WARN] [RealisticSeasons] Task #62 for RealisticSeasons v10.6.4 generated an exception
[04.12 01:22:20] [Server] java.lang.NoClassDefFoundErrorcom/comphenix/protocol/events/PacketListener
[04.12 01:22:20] [Server] 	at me.casperge.realisticseasons.Version.setupChunkPacketEvent(Version.java:175) ~[RealisticSeasons-10.6.4.jar:?]
[04.12 01:22:20] [Server] 	at me.casperge.realisticseasons.RealisticSeasons.enable(RealisticSeasons.java:255) ~[RealisticSeasons-10.6.4.jar:?]
[04.12 01:22:20] [Server] 	at me.casperge.realisticseasons.RealisticSeasons$1.run(RealisticSeasons.java:163) ~[RealisticSeasons-10.6.4.jar:?]
[04.12 01:22:20] [Server] 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:22:20] [Server] 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:22:20] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1097) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:22:20] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:22:20] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

2. after trying to run the /winter command it overloaded the memory  and caused the server to crash, is my guess. I think it could be a memory leak? but not for sure. here is the error that's thrown
[04.12 01:27:53] [Server] [WARN] [RealisticSeasons] Task #7431 for RealisticSeasons v10.6.4 generated an exception
[04.12 01:27:53] [Server] java.lang.NullPointerExceptionCannot invoke "me.casperge.realisticseasons.data.chunksaver.ChunkDataHandler.logChunk(me.casperge.realisticseasons.season.SeasonChunk)" because the return value of "me.casperge.realisticseasons.RealisticSeasons.getAsyncChunkHandler()" is null
[04.12 01:27:53] [Server] 	at me.casperge.realisticseasons.runnables.WinterBlockTicker.run(WinterBlockTicker.java:184) ~[RealisticSeasons-10.6.4.jar:?]
[04.12 01:27:53] [Server] 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:27:53] [Server] 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:27:53] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:27:53] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:27:53] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:27:53] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:27:53] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
[04.12 01:27:53] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04.12 01:27:53] [Server] [WARN] [RealisticSeasons] Task #7431 for RealisticSeasons v10.6.4 generated an exception

**Comment by casperge** [comment]
Hello, can you try updating your protocollib to their latest developer build? There should be a small link somewhere on their spigot page
