### ISSUE TITLE
does not work on local server

### ISSUE THREAD

**Issue by Patatesli** [casperge/RealisticSeasons-issues#228]
It doesn't work on my local server

 [RealisticSeasons] Task #8 for RealisticSeasons v10.7.6 generated an exception
java.lang.NumberFormatException: For input string: "we²ght:0.3"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_402-402]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_402-402]
        at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_402-402]
        at me.casperge.realisticseasons.data.Settings.load(Settings.java:350) ~[?:?]
        at me.casperge.realisticseasons.data.Settings.<init>(Settings.java:175) ~[?:?]
        at me.casperge.realisticseasons.RealisticSeasons.enable(RealisticSeasons.java:218) ~[?:?]
        at me.casperge.realisticseasons.RealisticSeasons$1.run(RealisticSeasons.java:172) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1179) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402-402]

It says so in the game too, when you type /rs set summer

When the game is hard it only says /rs

**Comment by casperge** [comment]
Hello! Thank you for waiting, I am working tomorrow and I will try to fix your issue

**Comment by casperge** [comment]
Does it work on a hosted server?
