### ISSUE TITLE
block is not found on 1.21

### ISSUE THREAD

**Issue by xLuca08** [casperge/RealisticSeasons-issues#235]
Error Report

Error Type: NoSuchFieldError

Description:
The RealisticSeasons plugin is attempting to access a non-existent field recentTps in the DedicatedServer class. This field does not exist in the version of the Minecraft server being used (CraftBukkit 1.21).

Details:

- Error Message:
    java.lang.NoSuchFieldError: Class net.minecraft.server.dedicated.DedicatedServer does not have member field 'double[] recentTps'

- Affected Code:
at me.casperge.realisticseasons1_21_R1.NmsCode_21_R1.getTPS(NmsCode_21_R1.java:271)
at me.casperge.realisticseasons.runnables.SummerBlockTicker.run(SummerBlockTicker.java:117)
at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:77)
at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414)
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1382)
at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:393)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1284)
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1036)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310)
at java.base/java.lang.Thread.run(Thread.java:1583)

Cause:
The RealisticSeasons plugin is not fully compatible with the version of the Minecraft server being used. Specifically, the DedicatedServer class lacks the recentTps field that the plugin expects.

Error Timestamp: [17:22:46]
Server Thread: WARN
Plugin Version: RealisticSeasons v11.0.0
Minecraft Server Version: CraftBukkit 1.21-R0.1-SNAPSHOT

Stacktrace:
java.lang.NoSuchFieldError: Class net.minecraft.server.dedicated.DedicatedServer does not have member field 'double[] recentTps'
        at me.casperge.realisticseasons1_21_R1.NmsCode_21_R1.getTPS(NmsCode_21_R1.java:271) ~[?:?]
        at me.casperge.realisticseasons.runnables.SummerBlockTicker.run(SummerBlockTicker.java:117) ~[?:?]
        at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1382) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:393) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1284) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1036) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by casperge** [comment]
Fixed
