### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Wgis** [casperge/RealisticSeasons-issues#88]
[23:08:00 ERROR]: Could not pass event EntityTargetLivingEntityEvent to RealisticSeasons v7.7
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getType()" because the return value of "org.bukkit.event.entity.EntityTargetEvent.getTarget()" is null
        at me.casperge.realisticseasons.event.EntityEvents.onTarget(EntityEvents.java:187) ~[RealisticSeasons-7.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1311.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-59]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.Mob.setTarget(Mob.java:275) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.setTarget(Wolf.java:132) ~[?:?]
        at net.minecraft.world.entity.ai.goal.target.TargetGoal.stop(TargetGoal.java:93) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.stop(WrappedGoal.java:47) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:108) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:854) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3237) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:628) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:63) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.aiStep(Wolf.java:199) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2893) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:396) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.tick(Wolf.java:215) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1125) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:667) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:647) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-59]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Wgis** [comment]
Sorry, add Bug label

**Comment by casperge** [comment]
Fixed in 7.8 that just released
